#!/bin/sh

# Settings
music_library="$HOME/music"
export FIFO_UEBERZUG="/tmp/mpd-ueberzug"

cover_path=''
export_cover_path='/tmp/mpd_cover.jpg'

find_cover_image() {
    file="$(mpc --format %file% current)"
    if [ -z "$file" ]; then return; fi

    # If no embedded art was found we look inside the music file's directory
    album="$(mpc --format %album% current)"
    album_dir="${file%/*}"
    album_dir="$music_library/$album_dir"
    found_covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f \
    -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\\(jpe?g\|png\|gif\|bmp\)" \; )"
    cover_path="$(echo "$found_covers" | head -n1)"
    if [ -n "$cover_path" ]; then
        return
    fi

    # First we check if the audio file has an embedded album art
    ext=$(echo "$file" | sed 's/^.*\.//')
    if [ "$ext" = "flac" ]; then
        # since FFMPEG cannot export embedded FLAC art we use metaflac
        metaflac --export-picture-to="$export_cover_path" \
            "$music_library/$file" &&
            cover_path="$export_cover_path" && return
    else
        ffmpeg -an -y -i "$music_library/$file" "$export_cover_path" &> /dev/null &&
            cover_path="$export_cover_path" && return
    fi
}

find_cover_image

if [ -n "$cover_path" ]; then
    cover_path=$cover_path "$HOME/.config/ncmpcpp/scripts/notify" &
    cover_path=$cover_path "$HOME/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp_cover_art.sh"
fi
